


export const SAVE_BRANCH_REQUEST = 'SAVE_BRANCH_REQUEST';
export const FETCH_BRANCH_REQUEST = 'FETCH_BRANCH_REQUEST';
export const UPDATE_BRANCH_REQUEST = 'UPDATE_BRANCH_REQUEST';
export const DELETE_BRANCH_REQUEST = 'DELETE_BRANCH_REQUEST';
export const BRANCH_SUCCESS = 'BRANCH_SUCCESS';
export const BRANCH_FAILURE = 'BRANCH_FAILURE';

export const FETCH_LANGUAGES_REQUEST = 'FETCH_LANGUAGES_REQUEST';
export const LANGUAGES_SUCCESS = 'LANGUAGES_SUCCESS';
export const LANGUAGES_FAILURE = 'LANGUAGES_FAILURE';

export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
export const GENRES_SUCCESS = 'GENRES_SUCCESS';
export const GENRES_FAILURE = 'GENRES_FAILURE';