export const SAVE_SWEET_REQUEST = 'SAVE_SWEET_REQUEST';
export const FETCH_SWEET_REQUEST = 'FETCH_SWEET_REQUEST';
export const UPDATE_SWEET_REQUEST = 'UPDATE_SWEET_REQUEST';
export const DELETE_SWEET_REQUEST = 'DELETE_SWEET_REQUEST';
export const SWEET_SUCCESS = 'SWEET_SUCCESS';
export const SWEET_FAILURE = 'SWEET_FAILURE';

export const FETCH_LANGUAGES_REQUEST = 'FETCH_LANGUAGES_REQUEST';
export const LANGUAGES_SUCCESS = 'LANGUAGES_SUCCESS';
export const LANGUAGES_FAILURE = 'LANGUAGES_FAILURE';

export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
export const GENRES_SUCCESS = 'GENRES_SUCCESS';
export const GENRES_FAILURE = 'GENRES_FAILURE';